# 서울시 범죄 현황 분석

* 데이터 획득
* pandas를 이용하여 데이터 정리하기
* 지도 정보를 얻을 수 있는 Google Maps

In [1]:
import numpy as np
import pandas as pd

In [3]:
crime_anal_police = pd.read_csv('data/section2/02. crime_in_Seoul.csv', thousands=',', encoding='euc-kr')
crime_anal_police.head()

    관서명  살인 발생  살인 검거  강도 발생  강도 검거  강간 발생  강간 검거  절도 발생  절도 검거  폭력 발생  폭력 검거
0   중부서      2      2      3      2    105     65   1395    477   1355   1170
1   종로서      3      3      6      5    115     98   1070    413   1278   1070
2  남대문서      1      0      6      4     65     46   1153    382    869    794
3  서대문서      2      2      5      4    154    124   1812    738   2056   1711
4   혜화서      3      2      5      4     96     63   1114    424   1015    861

### Google maps 를 이용해 주소와 위도, 경도 정보 얻기
* pip install googlemaps   << 설치

In [5]:
import googlemaps

gmaps_key = 'AIzaSyDdXzuX6wHie4AzkrNPtlO2WPEgywYR19Y'
gmaps = googlemaps.Client(key=gmaps_key)

# 구글 맵을 사용해 '서울중부경찰서' 단어 검색
gmaps.geocode('서울중부경찰서', language='ko')

[{'address_components': [{'long_name': '２７',
    'short_name': '２７',
    'types': ['premise']},
   {'long_name': '수표로',
    'short_name': '수표로',
    'types': ['political', 'sublocality', 'sublocality_level_4']},
   {'long_name': '을지로동',
    'short_name': '을지로동',
    'types': ['political', 'sublocality', 'sublocality_level_2']},
   {'long_name': '중구',
    'short_name': '중구',
    'types': ['political', 'sublocality', 'sublocality_level_1']},
   {'long_name': '서울특별시',
    'short_name': '서울특별시',
    'types': ['administrative_area_level_1', 'political']},
   {'long_name': '대한민국',
    'short_name': 'KR',
    'types': ['country', 'political']},
   {'long_name': '100-032',
    'short_name': '100-032',
    'types': ['postal_code']}],
  'formatted_address': '대한민국 서울특별시 중구 을지로동 수표로 27',
  'geometry': {'location': {'lat': 37.5636465, 'lng': 126.9895796},
   'location_type': 'ROOFTOP',
   'viewport': {'northeast': {'lat': 37.56499548029149,
     'lng': 126.9909285802915},
    'southwest': {'lat': 37.56229751970849, 'lng': 126.9882306197085}}},
  'place_id': 'ChIJc-9q5uSifDURLhQmr5wkXmc',
  'types': ['establishment', 'point_of_interest', 'police']}]

In [9]:
station_name=[]

for name in crime_anal_police['관서명']:
    tmp_name = '서울'+str(name[:-1]) + '경찰서'
    station_name.append(tmp_name)
    
station_name

['서울중부경찰서',
 '서울종로경찰서',
 '서울남대문경찰서',
 '서울서대문경찰서',
 '서울혜화경찰서',
 '서울용산경찰서',
 '서울성북경찰서',
 '서울동대문경찰서',
 '서울마포경찰서',
 '서울영등포경찰서',
 '서울성동경찰서',
 '서울동작경찰서',
 '서울광진경찰서',
 '서울서부경찰서',
 '서울강북경찰서',
 '서울금천경찰서',
 '서울중랑경찰서',
 '서울강남경찰서',
 '서울관악경찰서',
 '서울강서경찰서',
 '서울강동경찰서',
 '서울종암경찰서',
 '서울구로경찰서',
 '서울서초경찰서',
 '서울양천경찰서',
 '서울송파경찰서',
 '서울노원경찰서',
 '서울방배경찰서',
 '서울은평경찰서',
 '서울도봉경찰서',
 '서울수서경찰서']

In [10]:
station_address = []
station_lat = []
station_lng = []

for name in station_name:
    tmp = gmaps.geocode(name, language='ko')
    station_address.append(tmp[0].get("formatted_address"))
    
    tmp_loc=tmp[0].get("geometry")
    station_lat.append(tmp_loc['location']['lat'])
    
    station_lng.append(tmp_loc['location']['lng'])
    
    print(name + '--->' + tmp[0].get("formatted_address"))

서울중부경찰서--->대한민국 서울특별시 중구 을지로동 수표로 27
서울종로경찰서--->대한민국 서울특별시 종로구 종로1.2.3.4가동 율곡로 46
서울남대문경찰서--->대한민국 서울특별시 중구 남대문로5가 한강대로 410
서울서대문경찰서--->대한민국 서울특별시 서대문구 미근동 통일로 113
서울혜화경찰서--->대한민국 서울특별시 종로구 종로1.2.3.4가동 창경궁로 112-16
서울용산경찰서--->대한민국 서울특별시 용산구 원효로1가 25
서울성북경찰서--->대한민국 서울특별시 성북구 삼선동5가 301
서울동대문경찰서--->대한민국 서울특별시 동대문구 청량리동 약령시로21길 29
서울마포경찰서--->대한민국 서울특별시 마포구 아현동 618-1
서울영등포경찰서--->대한민국 서울특별시 영등포구 당산동3가 2-11
서울성동경찰서--->대한민국 서울특별시 성동구 행당1동 왕십리광장로 9
서울동작경찰서--->대한민국 서울특별시 동작구 노량진동 72
서울광진경찰서--->대한민국 서울특별시 광진구 구의1동 자양로 167
서울서부경찰서--->대한민국 서울특별시 은평구 대조동 통일로 757
서울강북경찰서--->대한민국 서울특별시 강북구 번1동 415-15
서울금천경찰서--->대한민국 서울특별시 관악구 신림동 544
서울중랑경찰서--->대한민국 서울특별시 중랑구 신내1동 신내역로3길 40-10
서울강남경찰서--->대한민국 서울특별시 강남구 대치동 998
서울관악경찰서--->대한민국 서울특별시 관악구 봉천동
서울강서경찰서--->대한민국 서울특별시 양천구 신월동 화곡로 73
서울강동경찰서--->대한민국 서울특별시 강동구 성내1동 성내로 57
서울종암경찰서--->대한민국 서울특별시 성북구 종암동 종암로 135
서울구로경찰서--->대한민국 서울특별시 구로구 가마산로 235
서울서초경찰서--->대한민국 서울특별시 서초구 서초3동 반포대로 179
서울양천경찰서--->대한민국 서울특별시 양천구 신정6동 목동동로 99
서울송파경찰서--->대한민국 서울특별시 송파구 가락본동 9
서울노원경찰서--->대한민국 서울특별시 노원구 하계동 노원로 283
서울방배경찰서--->대한민국 서울특별시 서초구 방배동 동작대로 204
서울은평경찰서--->대한민국 서울특별시 은평구 불광2동 연서로 365
서울도봉경찰서--->대한민국 서울특별시 도봉구 창4동 노해로 403
서울수서경찰서--->대한민국 서울특별시 강남구 개포동 개포로 617

In [11]:
station_lat

[37.5636465,
 37.5755578,
 37.5547584,
 37.5647848,
 37.5718401,
 37.538649,
 37.5897271,
 37.58506149999999,
 37.550814,
 37.5257884,
 37.5617309,
 37.5130685,
 37.542873,
 37.6128611,
 37.6373881,
 37.4814051,
 37.618692,
 37.5094352,
 37.4743789,
 37.5397827,
 37.528511,
 37.6020592,
 37.494931,
 37.4956054,
 37.5165667,
 37.5019065,
 37.6423605,
 37.4945959,
 37.6283597,
 37.6533589,
 37.49349]

In [12]:
station_lng

[126.9895796,
 126.9848674,
 126.9734981,
 126.9667762,
 126.9988562,
 126.966055,
 127.0161318,
 127.0457679,
 126.954028,
 126.901006,
 127.0363806,
 126.9428078,
 127.083821,
 126.9274951,
 127.0273238,
 126.9099508,
 127.1047136,
 127.0669578,
 126.9509748,
 126.8299968,
 127.1268224,
 127.0321577,
 126.886731,
 127.0052504,
 126.8656763,
 127.1271513,
 127.0714027,
 126.9831279,
 126.9287226,
 127.052682,
 127.0772119]

In [15]:
# 지역구별 추출
gu_name=[]

for name in station_address:
    tmp = name.split()
    
    tmp_gu = [gu for gu in tmp if gu[-1] == '구'][0]
    
    gu_name.append(tmp_gu)
    
    
crime_anal_police['구별'] = gu_name
crime_anal_police.head()

,관서명,살인 발생,살인 검거,강도 발생,강도 검거,강간 발생,강간 검거,절도 발생,절도 검거,폭력 발생,폭력 검거,구별
0,중부서,2,2,3,2,105,65,1395,477,1355,1170,중구
1,종로서,3,3,6,5,115,98,1070,413,1278,1070,종로구
2,남대문서,1,0,6,4,65,46,1153,382,869,794,중구
3,서대문서,2,2,5,4,154,124,1812,738,2056,1711,서대문구
4,혜화서,3,2,5,4,96,63,1114,424,1015,861,종로구

In [17]:
crime_anal_police[crime_anal_police['관서명']=='금천서']

,관서명,살인 발생,살인 검거,강도 발생,강도 검거,강간 발생,강간 검거,절도 발생,절도 검거,폭력 발생,폭력 검거,구별
15,금천서,3,4,6,6,151,122,1567,888,2054,1776,관악구

In [18]:
# 금천서는 관악구가 아닌 금천구에 있기 때문에 '구별' 변경
crime_anal_police.loc[crime_anal_police['관서명']=='금천서', ['구별']] = '금천구'
crime_anal_police[crime_anal_police['관서명']=='금천서']

,관서명,살인 발생,살인 검거,강도 발생,강도 검거,강간 발생,강간 검거,절도 발생,절도 검거,폭력 발생,폭력 검거,구별
15,금천서,3,4,6,6,151,122,1567,888,2054,1776,금천구

In [21]:
# 파일명으로 저장함으로써 백업
crime_anal_police.to_csv('data/section2/02. crime_in_Seoul_include_gu_name.csv', sep=',', encoding='utf-8')

,관서명,살인 발생,살인 검거,강도 발생,강도 검거,강간 발생,강간 검거,절도 발생,절도 검거,폭력 발생,폭력 검거,구별
0,중부서,2,2,3,2,105,65,1395,477,1355,1170,중구
1,종로서,3,3,6,5,115,98,1070,413,1278,1070,종로구
2,남대문서,1,0,6,4,65,46,1153,382,869,794,중구
3,서대문서,2,2,5,4,154,124,1812,738,2056,1711,서대문구
4,혜화서,3,2,5,4,96,63,1114,424,1015,861,종로구

In [22]:
crime_anal_raw = pd.read_csv('data/section2/02. crime_in_Seoul_include_gu_name.csv',
                            encoding='utf-8')
crime_anal_raw.head()

,Unnamed: 0,관서명,살인 발생,살인 검거,강도 발생,강도 검거,강간 발생,강간 검거,절도 발생,절도 검거,폭력 발생,폭력 검거,구별
0,0,중부서,2,2,3,2,105,65,1395,477,1355,1170,중구
1,1,종로서,3,3,6,5,115,98,1070,413,1278,1070,종로구
2,2,남대문서,1,0,6,4,65,46,1153,382,869,794,중구
3,3,서대문서,2,2,5,4,154,124,1812,738,2056,1711,서대문구
4,4,혜화서,3,2,5,4,96,63,1114,424,1015,861,종로구

In [23]:
crime_anal_raw = pd.read_csv('data/section2/02. crime_in_Seoul_include_gu_name.csv',
                            encoding='utf-8', index_col=0)

crime_anal = pd.pivot_table(crime_anal_raw, index='구별', aggfunc=np.sum)
crime_anal.head()

     강간 검거  강간 발생  강도 검거  강도 발생  살인 검거  살인 발생  절도 검거  절도 발생  폭력 검거  폭력 발생
구별
강남구    349    449     18     21     10     13   1650   3850   3705   4284
강동구    123    156      8      6      3      4    789   2366   2248   2712
강북구    126    153     13     14      8      7    618   1434   2348   2649
관악구    221    320     14     12      8      9    827   2706   2642   3298
광진구    220    240     26     14      4      4   1277   3026   2180   2625

In [24]:
crime_anal['강간검거율'] = crime_anal['강간 검거'] / crime_anal['강간 발생'] * 100
crime_anal['강도검거율'] = crime_anal['강도 검거'] / crime_anal['강도 발생'] * 100
crime_anal['살인검거율'] = crime_anal['살인 검거'] / crime_anal['살인 발생'] * 100
crime_anal['절도검거율'] = crime_anal['절도 검거'] / crime_anal['절도 발생'] * 100
crime_anal['폭력검거율'] = crime_anal['폭력 검거'] / crime_anal['폭력 발생'] * 100

del crime_anal['강간 검거']
del crime_anal['강도 검거']
del crime_anal['살인 검거']
del crime_anal['절도 검거']
del crime_anal['폭력 검거']

crime_anal.head()

,강간 발생,강도 발생,살인 발생,절도 발생,폭력 발생,강간검거율,강도검거율,살인검거율,절도검거율,폭력검거율
구별,,,,,,,,,,
강남구,449,21,13,3850,4284,77.728285,85.714286,76.923077,42.857143,86.484594
강동구,156,6,4,2366,2712,78.846154,133.333333,75.000000,33.347422,82.890855
강북구,153,14,7,1434,2649,82.352941,92.857143,114.285714,43.096234,88.637222
관악구,320,12,9,2706,3298,69.062500,116.666667,88.888889,30.561715,80.109157
광진구,240,14,4,3026,2625,91.666667,185.714286,100.000000,42.200925,83.047619

In [25]:
# 100 이 넘는 수치는 100으로 처리
con_list = ['강간검거율','강도검거율','살인검거율','절도검거율','폭력검거율']

for column in con_list:
    crime_anal.loc[crime_anal[column] > 100, column] = 100

crime_anal.head()

,강간 발생,강도 발생,살인 발생,절도 발생,폭력 발생,강간검거율,강도검거율,살인검거율,절도검거율,폭력검거율
구별,,,,,,,,,,
강남구,449,21,13,3850,4284,77.728285,85.714286,76.923077,42.857143,86.484594
강동구,156,6,4,2366,2712,78.846154,100.000000,75.000000,33.347422,82.890855
강북구,153,14,7,1434,2649,82.352941,92.857143,100.000000,43.096234,88.637222
관악구,320,12,9,2706,3298,69.062500,100.000000,88.888889,30.561715,80.109157
광진구,240,14,4,3026,2625,91.666667,100.000000,100.000000,42.200925,83.047619

In [26]:
crime_anal.rename(columns = {'강간 발생': '강간',
                             '강도 발생': '강도',
                            '살인 발생': '살인',
                            '절도 발생': '절도',
                            '폭력 발생': '폭력'}, inplace=True)

crime_anal.head()

,강간,강도,살인,절도,폭력,강간검거율,강도검거율,살인검거율,절도검거율,폭력검거율
구별,,,,,,,,,,
강남구,449,21,13,3850,4284,77.728285,85.714286,76.923077,42.857143,86.484594
강동구,156,6,4,2366,2712,78.846154,100.000000,75.000000,33.347422,82.890855
강북구,153,14,7,1434,2649,82.352941,92.857143,100.000000,43.096234,88.637222
관악구,320,12,9,2706,3298,69.062500,100.000000,88.888889,30.561715,80.109157
광진구,240,14,4,3026,2625,91.666667,100.000000,100.000000,42.200925,83.047619

In [39]:
# 데이터 다듬기, 정규화
# pip install sklearn
# pip install scipy
from sklearn import preprocessing

col = ['강간','강도','살인','절도','폭력']

x = crime_anal[col].values
min_max_scaler = preprocessing.MinMaxScaler()

# MinMaxScaler => 최소, 최대값을 이용해서 정규화
x_scaled = min_max_scaler.fit_transform(x.astype(float))
crime_anal_norm = pd.DataFrame(x_scaled, columns=col, index=crime_anal.index)

col2 = ['강간검거율','강도검거율','살인검거율','절도검거율','폭력검거율']
crime_anal_norm[col2] = crime_anal[col2]
crime_anal_norm.head()

,강간,강도,살인,절도,폭력,강간검거율,강도검거율,살인검거율,절도검거율,폭력검거율
구별,,,,,,,,,,
강남구,1.000000,0.941176,0.916667,0.953472,0.661386,77.728285,85.714286,76.923077,42.857143,86.484594
강동구,0.155620,0.058824,0.166667,0.445775,0.289667,78.846154,100.000000,75.000000,33.347422,82.890855
강북구,0.146974,0.529412,0.416667,0.126924,0.274769,82.352941,92.857143,100.000000,43.096234,88.637222
관악구,0.628242,0.411765,0.583333,0.562094,0.428234,69.062500,100.000000,88.888889,30.561715,80.109157
광진구,0.397695,0.529412,0.166667,0.671570,0.269094,91.666667,100.000000,100.000000,42.200925,83.047619

In [41]:
# 1장에서 한 결과값에 '구'별로 묶어서 데이터 합치기
result_CCTV = pd.read_csv('data/section2/01. CCTV_result.csv', encoding='UTF-8', index_col='구별')

crime_anal_norm[['인구수', 'CCTV']] = result_CCTV[['인구수', '소계']]
crime_anal_norm.head()

,강간,강도,살인,절도,폭력,강간검거율,강도검거율,살인검거율,절도검거율,폭력검거율,인구수,CCTV
구별,,,,,,,,,,,,
강남구,1.000000,0.941176,0.916667,0.953472,0.661386,77.728285,85.714286,76.923077,42.857143,86.484594,570500.0,2780
강동구,0.155620,0.058824,0.166667,0.445775,0.289667,78.846154,100.000000,75.000000,33.347422,82.890855,453233.0,773
강북구,0.146974,0.529412,0.416667,0.126924,0.274769,82.352941,92.857143,100.000000,43.096234,88.637222,330192.0,748
관악구,0.628242,0.411765,0.583333,0.562094,0.428234,69.062500,100.000000,88.888889,30.561715,80.109157,525515.0,1496
광진구,0.397695,0.529412,0.166667,0.671570,0.269094,91.666667,100.000000,100.000000,42.200925,83.047619,372164.0,707

In [42]:
col=['강간','강도','살인','절도','폭력']
crime_anal_norm['범죄'] = np.sum(crime_anal_norm[col], axis=1)
crime_anal_norm.head()

,강간,강도,살인,절도,폭력,강간검거율,강도검거율,살인검거율,절도검거율,폭력검거율,인구수,CCTV,범죄
구별,,,,,,,,,,,,,
강남구,1.000000,0.941176,0.916667,0.953472,0.661386,77.728285,85.714286,76.923077,42.857143,86.484594,570500.0,2780,4.472701
강동구,0.155620,0.058824,0.166667,0.445775,0.289667,78.846154,100.000000,75.000000,33.347422,82.890855,453233.0,773,1.116551
강북구,0.146974,0.529412,0.416667,0.126924,0.274769,82.352941,92.857143,100.000000,43.096234,88.637222,330192.0,748,1.494746
관악구,0.628242,0.411765,0.583333,0.562094,0.428234,69.062500,100.000000,88.888889,30.561715,80.109157,525515.0,1496,2.613667
광진구,0.397695,0.529412,0.166667,0.671570,0.269094,91.666667,100.000000,100.000000,42.200925,83.047619,372164.0,707,2.034438

In [52]:
col = ['강간검거율','강도검거율','살인검거율','절도검거율','폭력검거율']
crime_anal_norm['검거'] = np.sum(crime_anal_norm[col], axis=1)
crime_anal_norm

,강간,강도,살인,절도,폭력,강간검거율,강도검거율,살인검거율,절도검거율,폭력검거율,인구수,CCTV,범죄,검거
구별,,,,,,,,,,,,,,
강남구,1.000000,0.941176,0.916667,0.953472,0.661386,77.728285,85.714286,76.923077,42.857143,86.484594,570500.0,2780,4.472701,369.707384
강동구,0.155620,0.058824,0.166667,0.445775,0.289667,78.846154,100.000000,75.000000,33.347422,82.890855,453233.0,773,1.116551,370.084431
강북구,0.146974,0.529412,0.416667,0.126924,0.274769,82.352941,92.857143,100.000000,43.096234,88.637222,330192.0,748,1.494746,406.943540
관악구,0.628242,0.411765,0.583333,0.562094,0.428234,69.062500,100.000000,88.888889,30.561715,80.109157,525515.0,1496,2.613667,368.622261
광진구,0.397695,0.529412,0.166667,0.671570,0.269094,91.666667,100.000000,100.000000,42.200925,83.047619,372164.0,707,2.034438,416.915211
구로구,0.515850,0.588235,0.500000,0.435169,0.359423,58.362989,73.333333,75.000000,38.072805,80.877951,447874.0,1561,2.398678,325.647079
금천구,0.141210,0.058824,0.083333,0.172426,0.134074,80.794702,100.000000,100.000000,56.668794,86.465433,255082.0,1015,0.589867,423.928929
노원구,0.273775,0.117647,0.666667,0.386589,0.292268,61.421320,100.000000,100.000000,36.525308,85.530665,569384.0,1265,1.736946,383.477292
도봉구,0.000000,0.235294,0.083333,0.000000,0.000000,100.000000,100.000000,100.000000,44.967074,87.626093,348646.0,485,0.318627,432.593167
동대문구,0.204611,0.470588,0.250000,0.314061,0.250887,84.393064,100.000000,100.000000,41.090358,87.401884,369496.0,1294,1.490147,412.885306
동작구,0.527378,0.235294,0.250000,0.274376,0.100024,48.771930,55.555556,100.000000,35.442359,83.089005,412520.0,1091,1.387071,322.858850
마포구,0.553314,0.529412,0.500000,0.510434,0.353748,84.013605,71.428571,100.000000,31.819961,84.445189,389649.0,574,2.446908,371.707327
서대문구,0.149856,0.000000,0.000000,0.256244,0.134547,80.519481,80.000000,100.000000,40.728477,83.219844,327163.0,962,0.540647,384.467802
서초구,0.838617,0.235294,0.500000,0.537804,0.215654,63.358779,66.666667,75.000000,41.404175,87.453105,450310.0,1930,2.327368,333.882725
성동구,0.069164,0.235294,0.166667,0.186110,0.029558,94.444444,88.888889,100.000000,37.149969,86.538462,311244.0,1062,0.686793,407.021764
성북구,0.138329,0.000000,0.250000,0.247007,0.170726,82.666667,80.000000,100.000000,41.512605,83.974649,461260.0,1464,0.806061,388.153921
송파구,0.340058,0.470588,0.750000,0.744441,0.427524,80.909091,76.923077,90.909091,34.856437,84.552352,667483.0,618,2.732611,368.150048
양천구,0.806916,0.823529,0.666667,1.000000,1.000000,77.486911,84.210526,100.000000,48.469644,83.065080,479978.0,2034,4.297113,393.232162
영등포구,0.556196,1.000000,1.000000,0.650359,0.493024,62.033898,90.909091,85.714286,32.995951,82.894737,402985.0,904,3.699580,354.547963
용산구,0.265130,0.529412,0.250000,0.169004,0.133128,89.175258,100.000000,100.000000,37.700706,83.121951,244203.0,1624,1.346674,409.997915
은평구,0.184438,0.235294,0.083333,0.291139,0.275715,84.939759,66.666667,100.000000,37.147335,86.920467,494388.0,1873,1.069920,375.674229
종로구,0.314121,0.352941,0.333333,0.383510,0.190589,76.303318,81.818182,83.333333,38.324176,84.212822,162820.0,1002,1.574494,363.991830
중구,0.195965,0.235294,0.083333,0.508040,0.174273,65.294118,66.666667,66.666667,33.712716,88.309353,133240.0,671,1.196905,320.649519
중랑구,0.244957,0.352941,0.916667,0.366746,0.321589,79.144385,81.818182,92.307692,38.829040,84.545135,414503.0,660,2.202900,376.644434